apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-jwt-generator-deployment
  namespace: default
  labels:
    app: ldap-jwt-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ldap-jwt-generator
  template:
    metadata:
      labels:
        app: ldap-jwt-generator
    spec:
      serviceAccountName: default
      containers:
        - name: ldap-jwt-generator
          image: cagip/ldap-jwt-generator:latest
          ports:
            - containerPort: 8000
#          livenessProbe:
#            httpGet:
#              path: /ca
#              port: 8000
#              scheme: HTTPS
#            initialDelaySeconds: 3
#            periodSeconds: 1
          envFrom:
            - secretRef:
                name: ldap-jwt-generator-ldap-base-config # contains a password, so it's better to be a secret :)
          volumeMounts:
            - name: ldap-jwt-generator-tenant-registry
              mountPath: "/etc/ldap-jwt-generator/ldap-configs"
              readOnly: true
            - name: ldap-jwt-generator-jwt-signing-keys
              mountPath: "/etc/ldap-jwt-generator/signing-keys"
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: ldap-jwt-generator-tenant-registry
        - name: ldap-jwt-generator-signing-keys
          secret:
            secretName: ldap-jwt-generator-signing-keys
            items:
              - key: PRIVATE_KEY #Adapt this based on your secret "ldap-jwt-generator-signing-keys" 's key/values
                path: ecdsa-private-key.pem # Convention, do not edit (unless you change jwt\types.go)
              - key: PUBLIC_KEY #Adapt this based on your secret "ldap-jwt-generator-signing-keys" 's key/values
                path: ecdsa-public-key.pem # Convention, do not edit (unless you change jwt\types.go)

---
apiVersion: v1
kind: Service
metadata:
  name: ldap-jwt-generator-svc
  namespace: default
  labels:
    app: ldap-jwt-generator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: ldap-jwt-generator
